default_stages: [commit]
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.75.0
    hooks:
      # Rewrite Terraform configuration files to a canonical format and style
      - id: terraform_fmt

      # Validate the configuration files in a directory
      #- id: terraform_validate

      # Ensure coding standards are met
      - id: terraform_tflint
        args:
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_naming_convention'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_required_providers'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_workspace_remote'

      # Static analysis of potential security issues.
      - id: terraform_tfsec

      # Scan cloud infrastructure configurations to find misconfigurations
      - id: terraform_checkov
        args:
          - '--args=--skip-check CKV2_GHA_1'

      # Create README file documentation.
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=./README.md
          - --hook-config=--add-to-exiting-file=true
          - --hook-config=--create-file-if-not-exist=true
          - '--args=--lockfile=false'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      # Remove any spaces that are on the end of a line
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: CHANGELOG.md

      # Remove any blank lines on the end of file
      - id: end-of-file-fixer

      # Validate that all YAML files are syntactically correct
      - id: check-yaml

      # Validate that all JSON files are syntactically correct
      - id: check-json

      # Check for files that contain merge conflict strings.
      - id: check-merge-conflict
